[package]
name = "task-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { git = "https://github.com/emilk/egui", version = "0.33.3" }
sysinfo = "0.38.2"
tokio = { version = "1.49.0", features = ["full"] }
egui_extras = { git = "https://github.com/emilk/egui", features = [
    "default",
    "image",
] }
